"""Fix User-Review and Product-Review relationships

Revision ID: ea98a4c01194
Revises: 3becf9f84607
Create Date: 2025-10-13 12:37:51.252270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea98a4c01194'
down_revision: Union[str, Sequence[str], None] = '3becf9f84607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
